# Generated by Django 4.2.3 on 2023-08-13 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('rubro', models.CharField(choices=[('Tecnología', 'Tecnología'), ('Salud', 'Salud'), ('Educación', 'Educación'), ('Gastronomía', 'Gastronomía'), ('Construcción', 'Construcción'), ('Arte y Entretenimiento', 'Arte y Entretenimiento'), ('Ventas', 'Ventas'), ('Servicios', 'Servicios'), ('Pintura', 'Pintura'), ('Transporte', 'Transporte'), ('Plomeria', 'Plomeria'), ('Electricidad', 'Electricidad')], max_length=50)),
                ('habilidades', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('rubro', models.CharField(choices=[('Tecnología', 'Tecnología'), ('Salud', 'Salud'), ('Educación', 'Educación'), ('Gastronomía', 'Gastronomía'), ('Construcción', 'Construcción'), ('Arte y Entretenimiento', 'Arte y Entretenimiento'), ('Ventas', 'Ventas'), ('Servicios', 'Servicios'), ('Pintura', 'Pintura'), ('Transporte', 'Transporte'), ('Plomeria', 'Plomeria'), ('Electricidad', 'Electricidad')], max_length=50)),
                ('salario_ofrecido', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vinculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionBlog.trabajador')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionBlog.trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionBlog.trabajador')),
            ],
        ),
    ]
